name: airbnb_passport
description: Airbnb Host Passport made with Flutter
publish_to: none
version: 1.0.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_inset_shadow: ^2.0.3
  intl: ^0.20.0
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/avatars/
    - assets/apartments/
    - assets/fonts/

  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/PlusJakartaSans-Light.ttf
          weight: 300
        - asset: assets/fonts/PlusJakartaSans-ExtraLight.ttf
          weight: 200
